import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import ItemDescriptor from '../../models/ItemDescriptor.js';

const ITEMS_SEED = [
  // ===========================================================================
  // MEDKITS (Аптечки) — категория 4
  // ===========================================================================
  {
    code: 'Bandage8723',
    name: 'Бинт',
    category: 4,
    price: 80,
    description: 'Простой бинт. Восстанавливает 10 HP.',
    modifiers: { healthInstant: 10 },
  },
  {
    code: 'Medkit5923',
    name: 'Аптечка',
    category: 4,
    price: 80,
    description: 'Стандартная аптечка. Восстанавливает 20 HP.',
    modifiers: { healthInstant: 20 },
  },
  {
    code: 'ArmyMedkit8923',
    name: 'Армейская аптечка',
    category: 4,
    price: 80,
    description: 'Армейская аптечка. Восстанавливает 30 HP.',
    modifiers: { healthInstant: 30 },
  },
  {
    code: 'Vinca6923',
    name: 'Таблетки Барвинок',
    category: 4,
    price: 80,
    description: 'Восстанавливает 40 HP и снимает 1 единицу радиации.',
    modifiers: { healthInstant: 40, radiationInstant: -1 },
  },
  {
    code: 'ScientificMedkit5623',
    name: 'Научная аптечка',
    category: 4,
    price: 80,
    description: 'Восстанавливает 50 HP и снимает 3 единицырадиации.',
    modifiers: { healthInstant: 50, radiationInstant: -3 },
  },

  // ===========================================================================
  // ANTIRADS (Антирады) — категория 7
  // ===========================================================================
  {
    code: 'Vodka4523',
    name: 'Водка Казаки',
    category: 7,
    price: 60,
    description: 'Восстанавливает -10 HP (урон) и снимает 1 единицурадиации.',
    modifiers: { healthInstant: -10, radiationInstant: -1 },
  },
  {
    code: 'AntiRad5323',
    name: 'Антирад',
    category: 7,
    price: 60,
    description: 'Мощное средство от радиации. Снимает 7 единиц, но наносит -20 HP.',
    modifiers: { healthInstant: -20, radiationInstant: -7 },
  },
  {
    code: 'Anabiotic5923',
    name: 'Анабиотик',
    category: 7,
    price: 60,
    description: 'Наносит -30 HP.',
    modifiers: { healthInstant: -30 },
  },

  // ===========================================================================
  // BOOSTERS (Бустеры) — категория 2
  // ===========================================================================
  {
    code: 'B190Radioprotectant6323',
    name: 'Радиопротектор Б190',
    category: 2,
    price: 200,
    isBooster: true,
    duration: 60 * 1000,
    description: 'Полная защита отрадиации на 60 секунд.',
    modifiers: { radiation: 0 },
  },
  {
    code: 'PsyBlock2623',
    name: 'Пси-блокада',
    category: 2,
    price: 200,
    isBooster: true,
    duration: 60 * 1000,
    description: 'Полная защита от ментальных воздействий на 60 секунд.',
    modifiers: { mental: 0 },
  },
  {
    code: 'IP2Antidote5823',
    name: 'Антидот ИП2',
    category: 2,
    price: 200,
    isBooster: true,
    duration: 60 * 1000,
    description: 'Полная защита от аномалий на 60 секунд.',
    modifiers: { anomaly: 0 },
  },
  {
    code: 'GreenSvobodaSerum8523',
    name: 'Настойка Радвинок',
    category: 2,
    price: 200,
    isBooster: true,
    duration: 120 * 60 * 1000,
    description: 'Увеличивает защиту отрадиации на 90% (множитель 0.1) на 120 минут.',
    modifiers: { radiation: 0.1 },
  },
  {
    code: 'YellowSvobodaSerum6323',
    name: 'Настойка Менвинок',
    category: 2,
    price: 200,
    isBooster: true,
    duration: 120 * 60 * 1000,
    description: 'Увеличивает защиту от ментальных воздействий на 90% на 120 минут.',
    modifiers: { mental: 0.1 },
  },

  // ===========================================================================
  // FILTERS (Фильтры) — категория 10
  // ===========================================================================
  {
    code: 'Respirator5923',
    name: 'Респиратор',
    category: 10,
    price: 250,
    isDevice: true,
    duration: 30 * 60 * 1000,
    description: 'Фильтр отрадиации 40% на 30 минут.',
    modifiers: { radiation: 0.6 },
  },
  {
    code: 'Gasmask5923',
    name: 'Противогаз',
    category: 10,
    price: 250,
    isDevice: true,
    duration: 60 * 60 * 1000,
    description: 'Фильтр отрадиации 60% на 60 минут.',
    modifiers: { radiation: 0.4 },
  },
  {
    code: 'Rebreather8423',
    name: 'Система замкнутого дыхания',
    category: 10,
    price: 250,
    isDevice: true,
    duration: 120 * 60 * 1000,
    description: 'Фильтр отрадиации 90% на 120 минут.',
    modifiers: { radiation: 0.1 },
  },

  // ===========================================================================
  // DEVICES (Приборы) — категория 11
  // ===========================================================================
  {
    code: 'PsionicHelmetMark6923',
    name: 'Пси-шлем М1',
    category: 11,
    price: 400,
    isDevice: true,
    duration: 30 * 60 * 1000,
    description: 'Защита от ментальных воздействий и контролёра на 30 минут.',
    modifiers: { mental: 0.01, controller: 0.7 },
  },
  {
    code: 'PsionicHelmetMark8523',
    name: 'Пси-шлем М2',
    category: 11,
    price: 400,
    isDevice: true,
    duration: 60 * 60 * 1000,
    description: 'Защита от ментальных, монолит и контролёр воздействий на 60 минут.',
    modifiers: { mental: 0.0, monolith: 0.01, controller: 0.4 },
  },

  // ===========================================================================
  // ARMORS (Броня) — категория 3
  // ===========================================================================

  // --- Простые ---
  {
    code: 'LeatherJacket4123',
    name: 'Кожаная куртка',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 60 * 60 * 1000,
    description: 'Простая кожаная куртка. Защита отрадиации 10%.',
    modifiers: { radiation: 0.9 },
  },
  {
    code: 'LeatherJacketLevel2',
    name: 'Кожаная куртка 2',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 90 * 60 * 1000,
    description: 'Улучшенная кожаная куртка.',
    modifiers: { radiation: 0.8, anomaly: 0.9 },
  },
  {
    code: 'LeatherJacketLevel3',
    name: 'Кожаная куртка 3',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 90 * 60 * 1000,
    description: 'Максимально улучшенная кожаная куртка.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'SSP99Ecologist5123',
    name: 'Комбинезон Эколог',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 60 * 60 * 1000,
    description: 'Комбинезон учёного-эколога.',
    modifiers: { radiation: 0.2, anomaly: 0.4, mental: 0.6 },
  },

  // --- Улучшенные ---
  {
    code: 'StalkerSuit8723',
    name: 'Комбез сталкера Заря',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 120 * 60 * 1000,
    description: 'Стандартный комбез сталкера.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'StalkerSuitLevel2',
    name: 'Комбез сталкера Заря lvl 2',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 150 * 60 * 1000,
    description: 'Улучшенный комбез сталкера.',
    modifiers: { radiation: 0.6, anomaly: 0.7, mental: 0.9 },
  },
  {
    code: 'StalkerSuitLevel3',
    name: 'Комбез сталкера Заря lvl 3',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 150 * 60 * 1000,
    description: 'Максимально улучшенный комбез сталкера.',
    modifiers: { radiation: 0.5, anomaly: 0.7, mental: 0.8 },
  },
  {
    code: 'SEVASuit2823',
    name: 'Комбинезон СЕВА',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 120 * 60 * 1000,
    description: 'Научный комбинезон СЕВА.',
    modifiers: { radiation: 0.5, anomaly: 0.6, mental: 0.7 },
  },
  {
    code: 'Exoskeleton4823',
    name: 'Экзоскелет',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 120 * 60 * 1000,
    description: 'Тяжёлый экзоскелет. Высокая защита + регенерация.',
    modifiers: { radiation: 0.7, anomaly: 0.6, mental: 0.9, health: 2 },
  },

  // --- Фракционные ---
  {
    code: 'BerillSuit2623',
    name: 'Бронекостюм Берилл',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Бронекостюм фракции Долг.',
    modifiers: { radiation: 0.8, anomaly: 0.8, mental: 0.8, health: 3 },
  },
  {
    code: 'MercSuit5623',
    name: 'Комбез наёмника',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Комбез наёмника.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'DutySuit5823',
    name: 'Комбез Долга',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Комбез фракции Долг.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'FreedomSuit2823',
    name: 'Комбез Свободы',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Комбез фракции Свобода.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'ClearSkySuit5723',
    name: 'Комбез Чистого Неба',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Комбез фракции Чистое Небо.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'BanditSuit5823',
    name: 'Плащ бандита',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Плащ бандита.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.9 },
  },
  {
    code: 'MonolithSuit6923',
    name: 'Комбез Монолита',
    category: 3,
    price: 800,
    isArmor: true,
    duration: 180 * 60 * 1000,
    description: 'Комбез фракции Монолит.',
    modifiers: { radiation: 0.7, anomaly: 0.8, mental: 0.01 },
  },

  // ===========================================================================
  // ARTIFACTS (Артефакты) — категория 1
  // ===========================================================================

  // --- Антирадные ---
  {
    code: 'Droplets854',
    name: 'Капли',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 2,
    description: 'Антирадный артефакт. Множительрадиации: 0.9 (10% защита).',
    modifiers: { radiation: 0.9 },
  },
  {
    code: 'Bubble156',
    name: 'Пузырь',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 5,
    description: 'Антирадный артефакт. Множительрадиации: 0.8.',
    modifiers: { radiation: 0.8 },
  },
  {
    code: 'Fireball785',
    name: 'Огненный шар',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 10,
    description: 'Антирадный артефакт. Множительрадиации: 0.7.',
    modifiers: { radiation: 0.7 },
  },
  {
    code: 'Crystal478',
    name: 'Кристалл',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 10,
    description: 'Антирадный артефакт. Множительрадиации: 0.6.',
    modifiers: { radiation: 0.6 },
  },
  {
    code: 'Thorn963',
    name: 'Колючка',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 10,
    description: 'Смешанный артефакт. Радиация x0.5, ментальное x1.25, аномалия x1.25.',
    modifiers: { radiation: 0.5, mental: 1.25, anomaly: 1.25 },
  },

  // --- Лечащие ---
  {
    code: 'Jellyfish254',
    name: 'Медуза',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 1,
    description: 'Лечащий артефакт. Регенерация здоровья +1.5.',
    modifiers: { health: 1.5 },
  },
  {
    code: 'Eye965',
    name: 'Глаз',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 2,
    description: 'Лечащий артефакт. Регенерация здоровья +2.',
    modifiers: { health: 2 },
  },
  {
    code: 'Kolobok749',
    name: 'Колобок',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 5,
    description: 'Лечащий артефакт. Регенерация здоровья +3.',
    modifiers: { health: 3 },
  },
  {
    code: 'Goldfish325',
    name: 'Золотая рыбка',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 15,
    description: 'Лечащий артефакт. Регенерация здоровья +4, защита от контролёра 0.1.',
    modifiers: { health: 4, controller: 0.1 },
  },
  {
    code: 'MamasBeads965',
    name: 'Мамины бусы',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 15,
    description: 'Лечащий артефакт. Регенерация здоровья +5, защита от бюрера 0.1.',
    modifiers: { health: 5, burer: 0.1 },
  },
  {
    code: 'Mica876',
    name: 'Слюда',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 20,
    description: 'Сложный артефакт. Много разных модификаторов.',
    modifiers: { health: 6, burer: 0.1, controller: 0.1, radiation: 1.25, mental: 1.25, anomaly: 1.25 },
  },

  // --- Противоаномальные ---
  {
    code: 'Spring635',
    name: 'Пружина',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 5,
    description: 'Противоаномальный артефакт. Радиация x1.1, аномалия x0.75.',
    modifiers: { radiation: 1.1, anomaly: 0.75 },
  },
  {
    code: 'Moonlight254',
    name: 'Лунный свет',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 10,
    description: 'Противоаномальный артефакт. Радиация x1.2, аномалия x0.5.',
    modifiers: { radiation: 1.2, anomaly: 0.5 },
  },

  // --- Противоментальные ---
  {
    code: 'StoneFlower835',
    name: 'Каменный цветок',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 5,
    description: 'Противоментальный артефакт. Радиация x1.2, ментальное x0.8.',
    modifiers: { radiation: 1.2, mental: 0.8 },
  },
  {
    code: 'Pe1licle149',
    name: 'Плёнка',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 10,
    description: 'Противоментальный артефакт. Радиация x1.4, ментальное x0.6.',
    modifiers: { radiation: 1.4, mental: 0.6 },
  },
  {
    code: 'NightStar853',
    name: 'Ночная звезда',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 15,
    description: 'Противоментальный артефакт. Радиация x1.6, ментальное x0.4.',
    modifiers: { radiation: 1.6, mental: 0.4 },
  },
  {
    code: 'Compass478',
    name: 'Компас',
    category: 1,
    price: 500,
    isArtifact: true,
    xpPoints: 30,
    description: 'Уникальный артефакт. Множественные модификаторы.',
    modifiers: { radiation: 2, mental: 0.4, anomaly: 0.01 },
  },

  // --- Радиоактивные (излучатели) ---
  {
    code: 'Shell365',
    name: 'Пустышка',
    category: 1,
    price: 500,
    isArtifact: true,
    description: 'Радиоактивный артефакт. Излучение: +1.',
    modifiers: { radiationEmitter: 1 },
  },
  {
    code: 'AlteredInsulator148',
    name: 'Радиоактивный изолятор',
    category: 1,
    price: 500,
    isArtifact: true,
    description: 'Радиоактивный артефакт. Излучение: +7.',
    modifiers: { radiationEmitter: 7 },
  },
  {
    code: 'BlackEnergy964',
    name: 'Чёрная энергия',
    category: 1,
    price: 500,
    isArtifact: true,
    description: 'Радиоактивный артефакт. Излучение: +14.',
    modifiers: { radiationEmitter: 14 },
  },

  // ===========================================================================
  // UPGRADES (Обвес) — категория 6
  // ===========================================================================
  {
    code: 'Binoculars135',
    name: 'Бинокль',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Бинокль для наблюдения.',
  },
  {
    code: 'Optics135',
    name: 'Оптический прицел',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Оптический прицел.',
  },
  {
    code: 'Collimator854',
    name: 'Коллиматор',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Коллиматорный прицел.',
  },
  {
    code: 'NightVision786',
    name: 'Прибор ночного видения',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Прибор ночного видения.',
  },
  {
    code: 'WalkieTalkie259',
    name: 'Рация',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Рация для связи.',
  },
  {
    code: 'GrenadeLauncher548',
    name: 'Гранатомёт',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Подствольный гранатомёт.',
  },
  {
    code: 'medik1',
    name: 'Медик-навык',
    category: 6,
    price: 300,
    isConsumable: false,
    xpPoints: 0,
    description: 'Улучшение навыка медика.',
  },

  // ===========================================================================
  // FOOD (Еда) — категория 8
  // ===========================================================================
  {
    code: 'DeadRat8423',
    name: 'Дохлая крыса',
    category: 8,
    price: 40,
    description: 'Восстанавливает 30 HP, но добавляет 2 единицырадиации.',
    modifiers: { healthInstant: 30, radiationInstant: 2 },
  },
  {
    code: 'Bread9523',
    name: 'Батон',
    category: 8,
    price: 40,
    xpPoints: 1,
    description: 'Батон хлеба. Восстанавливает 3 HP.',
    modifiers: { healthInstant: 3 },
  },
  {
    code: 'Sausage2423',
    name: 'Колбаса',
    category: 8,
    price: 40,
    xpPoints: 2,
    description: 'Колбаса. Восстанавливает 6 HP.',
    modifiers: { healthInstant: 6 },
  },
  {
    code: 'CannedMeat4823',
    name: 'Консерва',
    category: 8,
    price: 40,
    xpPoints: 3,
    description: 'Консервированное мясо. Восстанавливает 9 HP.',
    modifiers: { healthInstant: 9 },
  },
  {
    code: 'Doktorskaja4823',
    name: 'Докторская',
    category: 8,
    price: 40,
    xpPoints: 5,
    description: 'Колбаса докторская. Восстанавливает 12 HP.',
    modifiers: { healthInstant: 12 },
  },
  {
    code: 'Delikates4823',
    name: 'Деликатес',
    category: 8,
    price: 40,
    xpPoints: 6,
    description: 'Деликатесная колбаса. Восстанавливает 15 HP.',
    modifiers: { healthInstant: 15 },
  },
  {
    code: 'Hercules5923',
    name: 'Геркулес',
    category: 8,
    price: 40,
    isBooster: true,
    duration: 30 * 60 * 1000,
    description: 'Бустер здоровья на 30 минут. Регенерация +1.5.',
    modifiers: { health: 1.5 },
  },
  {
    code: 'EnergyDrink6323',
    name: 'Энергетик Сталкер',
    category: 8,
    price: 40,
    isBooster: true,
    duration: 30 * 60 * 1000,
    description: 'Бустер здоровья на 30 минут. Регенерация +2.',
    modifiers: { health: 2 },
  },
  {
    code: 'RedDevil3423',
    name: 'Левый энергетик',
    category: 8,
    price: 40,
    isBooster: true,
    duration: 15 * 60 * 1000,
    description: 'Бустер на 15 минут. Регенерация +0.5, норадиации x0.5.',
    modifiers: { health: 0.5, radiation: 0.5 },
  },

  // ===========================================================================
  // WEAPONS (Оружие) — категория 0
  // ===========================================================================
  {
    code: 'Knife845',
    name: 'Нож',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Холодное оружие.',
  },
  {
    code: 'Pistol845',
    name: 'Пистолет',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Пистолет.',
  },
  {
    code: 'Shotgun845',
    name: 'Дробовик',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Дробовик.',
  },
  {
    code: 'SubMachineGun359',
    name: 'Пистолет-пулемёт',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Пистолет-пулемёт.',
  },
  {
    code: 'AKtype148',
    name: 'Калаш',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Автомат Калашникова.',
  },
  {
    code: 'M4type148',
    name: 'М4',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Автомат M4.',
  },
  {
    code: 'VAL648',
    name: 'Вал',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Специальный автомат Вал.',
  },
  {
    code: 'SniperGun358',
    name: 'Снайперская винтовка',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Снайперская винтовка.',
  },
  {
    code: 'MachineGun257',
    name: 'Пулемёт',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Пулемёт.',
  },
  {
    code: 'GaussGun458',
    name: 'Гаусс пушка',
    category: 0,
    price: 1000,
    isConsumable: false,
    xpPoints: 0,
    description: 'Гаусс-оружие.',
  },

  // ===========================================================================
  // AMMO (Боеприпасы) — категория 9
  // ===========================================================================
  {
    code: '9mm784',
    name: 'Пистолетные 9мм',
    category: 9,
    price: 50,
    xpPoints: 1,
    description: 'Патроны 9мм.',
  },
  {
    code: '12cal784',
    name: 'Картечь 12 калибр',
    category: 9,
    price: 50,
    xpPoints: 1,
    description: 'Патроны 12 калибра.',
  },
  {
    code: '545ak875',
    name: 'От АК 5.45',
    category: 9,
    price: 50,
    xpPoints: 1,
    description: 'Патроны 5.45 для АК.',
  },
  {
    code: '556nato875',
    name: 'От НАТО 5.56',
    category: 9,
    price: 50,
    xpPoints: 1,
    description: 'Патроны 5.56 NATO.',
  },
  {
    code: 'VALvintorez875',
    name: '9мм Вал',
    category: 9,
    price: 50,
    xpPoints: 1,
    description: 'Патроны 9мм для Вала.',
  },
  {
    code: '762mm875',
    name: '7.62 универсальные',
    category: 9,
    price: 50,
    xpPoints: 1,
    description: 'Патроны 7.62.',
  },
  {
    code: 'Gauss875',
    name: 'Гаусс патроны',
    category: 9,
    price: 50,
    xpPoints: 10,
    description: 'Гаусс-патроны. Добавляют 3 единицырадиации.',
    modifiers: { radiationInstant: 3 },
  },
  {
    code: 'BigBK875',
    name: 'Большой боекомплект',
    category: 9,
    price: 50,
    xpPoints: 20,
    description: 'Большой боекомплект.',
  },
  {
    code: 'F1grenade875',
    name: 'Ф1',
    category: 9,
    price: 50,
    xpPoints: 2,
    description: 'Граната Ф1.',
  },
  {
    code: 'Limonka875',
    name: 'Лимонка',
    category: 9,
    price: 50,
    xpPoints: 2,
    description: 'Граната РГД-5 (Лимонка).',
  },
  {
    code: 'Zazhigalka875',
    name: 'Зажигательная граната',
    category: 9,
    price: 50,
    xpPoints: 2,
    description: 'Зажигательная граната.',
  },
  {
    code: 'Podstvolka875',
    name: 'Выстрел к гранатомёту',
    category: 9,
    price: 50,
    xpPoints: 3,
    description: 'Подствольный гранатомётный выстрел.',
  },

  // ===========================================================================
  // HABAR (Хабар) — категория 5
  // ===========================================================================
  {
    code: 'Garmoshka85323',
    name: 'Губная гармошка',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 4,
    description: 'Потрёпанная губная гармошка.',
  },
  {
    code: 'Bag85323',
    name: 'Спальный мешок',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 5,
    description: 'Спальный мешок.',
  },
  {
    code: 'Gasoline85323',
    name: 'Канистра бензина',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 10,
    description: 'Канистра бензина.',
  },
  {
    code: 'Maps85323',
    name: 'Старая карта',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 15,
    description: 'Старая карта.',
  },
  {
    code: 'Guitar45823',
    name: 'Потрёпанная гитара',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 20,
    description: 'Потрёпанная гитара.',
  },
  {
    code: 'Instruments19323',
    name: 'Ящик с инструментами',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 30,
    description: 'Ящик с инструментами.',
  },
  {
    code: 'UnknownDevice91723',
    name: 'Непонятный прибор',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 40,
    description: 'Непонятный прибор.',
  },
  {
    code: 'InfoPDA45823',
    name: 'ПДА с важной инфой',
    category: 5,
    price: 200,
    isConsumable: false,
    xpPoints: 50,
    description: 'ПДА с важной информацией.',
  },

  // --- Карты Форта ---
  {
    code: 'map_1', name: 'Карта Форта 1', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_2', name: 'Карта Форта 2', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_3', name: 'Карта Форта 3', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_4', name: 'Карта Форта 4', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_5', name: 'Карта Форта 5', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_6', name: 'Карта Форта 6', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_7', name: 'Карта Форта 7', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_8', name: 'Карта Форта 8', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },
  {
    code: 'map_9', name: 'Карта Форта 9', category: 5, price: 200,
    isConsumable: false, xpPoints: 50, description: 'Карта локации Форт.',
  },

  // ===========================================================================
  // CALIBRATION (Калибровка) — категория DEVICES (11)
  // ===========================================================================
  {
    code: 'Calibrating0223',
    name: 'Калибровка -10%',
    category: 11,
    price: 400,
    isArtifact: true,
    xpPoints: 0,
    isConsumable: false,
    description: '-10% к некоторым угрозам.',
    modifiers: { radiation: 0.9, anomaly: 0.9, mental: 0.9, burer: 0.9, controller: 0.9, monolith: 0.9 },
  },
  {
    code: 'Calibrating5723',
    name: 'Калибровка -25%',
    category: 11,
    price: 400,
    isArtifact: true,
    xpPoints: 0,
    isConsumable: false,
    description: '-25% к некоторым угрозам.',
    modifiers: { radiation: 0.75, anomaly: 0.75, mental: 0.75, burer: 0.75, controller: 0.75, monolith: 0.75 },
  },
  {
    code: 'Calibrating0823',
    name: 'Калибровка -50%',
    category: 11,
    price: 400,
    isArtifact: true,
    xpPoints: 0,
    isConsumable: false,
    description: '-50% к некоторым угрозам.',
    modifiers: { radiation: 0.5, anomaly: 0.5, mental: 0.5, burer: 0.5, controller: 0.5, monolith: 0.5 },
  },
  {
    code: 'Calibrating5323',
    name: 'Калибровка -75%',
    category: 11,
    price: 400,
    isArtifact: true,
    xpPoints: 0,
    isConsumable: false,
    description: '-75% к некоторым угрозам.',
    modifiers: { radiation: 0.25, anomaly: 0.25, mental: 0.25, burer: 0.25, controller: 0.25, monolith: 0.25 },
  },
];

async function seed() {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB');

        for (const itemData of ITEMS_SEED) {
            await ItemDescriptor.findOneAndUpdate(
                { code: itemData.code },
                itemData,
                { upsert: true, new: true }
            );
        }
        console.log(`Seeded ${ITEMS_SEED.length} ItemDescriptors`);
    } catch (error) {
        console.error('Seed error:', error);
    } finally {
        await mongoose.connection.close();
    }
}

seed();
